---
deployment:
  tasks:
    - export BACKEND=/home/vdranjxy/comrades-backend
    - export FRONTEND=/home/vdranjxy/public_html
    - /bin/mkdir -p $BACKEND
    - /bin/cp -Rf backend/* $BACKEND/
    - /bin/cp -Rf frontend/dist/* $FRONTEND/
    - /bin/mkdir -p $BACKEND/tmp
    - /bin/touch $BACKEND/tmp/restart.txt
